/**
 * reicon-sync.js
 *
 * Reads Reicon icon source files (from node_modules/reicon or a directory
 * passed via REICON_SRC) and emits `src/icons/reicon-data.js`.
 *
 * The emitted file is the single source of truth for the icons used across
 * the app. It contains the raw SVG inner markup for each icon in two
 * weights: `O` (outline) and `F` (filled). At runtime we wrap that markup
 * with an <svg> tag, recolor `currentColor`, and render it as a base64 / data
 * URI `background-image`, which is the only reliable way to draw SVG inside a
 * WeChat mini program (no <svg> DOM node, no Image svg support).
 *
 * Reicon: https://reicon.dev | MIT License
 */
const fs = require('node:fs')
const path = require('node:path')

const ROOT = path.resolve(__dirname, '..')
const DEFAULT_SRC = path.join(ROOT, 'node_modules', 'reicon', 'icons')
const SRC = process.env.REICON_SRC || DEFAULT_SRC
const OUT = path.join(ROOT, 'src', 'icons', 'reicon-data.js')

// Icons baked into the app. Names follow Reicon's PascalCase export names.
const ICON_NAMES = [
  // App-level
  'Wheel',
  'Coins',
  'Compass',
  'Cards',
  'ShieldCheck',
  'WalletMoney',
  'MagicWand',
  'GemSparkle',
  // Ledger categories (expense)
  'ForkKnife',
  'Coffee',
  'TeaCup',
  'PizzaSlice',
  'ShoppingCart',
  'Bus',
  'Car',
  'BagShopping',
  'MedicalKit',
  'Pill',
  'Stethoscope',
  'Gamepad',
  'Music',
  'Film',
  'Headphones',
  'Home2',
  'Bed',
  'Sofa',
  'Book',
  'GraduationCap',
  'Notebook',
  // Ledger categories (income)
  'Bill',
  'WalletAdd',
  'Chart',
  'TrendUp',
  'MoneyRecive',
  'Money',
  'Dollar',
  'Safe',
  'Gift',
  'Cake',
  // Extras for the custom picker
  'Add',
  'Sparkle',
  'Star',
  'Heart',
  'Phone',
  'Computer',
  'Tv',
  'Moon',
  'Wallet',
  'More',
  'Target',
  'HeartPulse',
  'CalendarCheck',
  'Plus',
  'Minus',
  'Settings',
  'Clock',
  'Pen',
  'User',
  'Share',
  'Users',
]

function extractBlock(source, key) {
  // The Reicon source files hold the markup inside backticks: `O: \`<svg/>\``.
  // Build the pattern from plain strings so backticks don't clash with
  // template literal syntax.
  const bt = String.fromCharCode(96)
  const pattern = key + ':\\s*' + bt + '([\\s\\S]*?)' + bt
  const re = new RegExp(pattern)
  const match = source.match(re)
  return match ? match[1] : null
}

const record = {}
const missing = []

for (const name of ICON_NAMES) {
  const file = path.join(SRC, `${name}.js`)
  if (!fs.existsSync(file)) {
    missing.push(name)
    continue
  }
  const source = fs.readFileSync(file, 'utf8')
  const O = extractBlock(source, 'O')
  const F = extractBlock(source, 'F')
  record[name] = { O, F }
}

if (missing.length) {
  console.warn(`[reicon-sync] Missing icon source files: ${missing.join(', ')}`)
}

const body = Object.keys(record)
  .sort()
  .map((name) => {
    const icon = record[name]
    const o = icon.O ? JSON.stringify(icon.O) : 'null'
    const f = icon.F ? JSON.stringify(icon.F) : 'null'
    return `  ${name}: { O: ${o}, F: ${f} },`
  })
  .join('\n')

const banner = `/**
 * Auto-generated by scripts/reicon-sync.js — DO NOT EDIT.
 * Icons source: https://reicon.dev (MIT License), extracted from the
 * \`reicon\` npm package. Icon markup uses currentColor so it can be tinted.
 *
 * Regenerate with:  node scripts/reicon-sync.js
 */

export const REICON = {
${body}
}
`

fs.mkdirSync(path.dirname(OUT), { recursive: true })
fs.writeFileSync(OUT, banner, 'utf8')

console.log(`[reicon-sync] Wrote ${Object.keys(record).length} icons -> ${path.relative(ROOT, OUT)}`)
console.log(`[reicon-sync] Source: ${SRC}`)
